name: Daily News Digest
on:
  schedule:
    - cron:  '0 6 * * *'   # 06:00 UTC ≈ 08:00 Europe/Rome (handles DST)
permissions:
  contents: write   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with: { python-version: '3.x' }
    - run: pip install feedparser beautifulsoup4 requests
    - name: Run script
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python news_digest.py
    - name: Commit digest.txt
      run: |
        git config --global user.name  "github-actions"
        git config --global user.email "actions@github.com"
        git add digest.txt
        git commit -m "Auto‑update digest $(date -u +'%Y-%m-%d %H:%M')" || echo "No changes"
        git push
